name: ASF (5 accounts)

on:
  workflow_dispatch:  # Allows for manual triggering
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours (can adjust as needed)

jobs:
  run-asf:
    runs-on: ubuntu-latest  # Choose the appropriate runner (ubuntu for Linux, windows-latest for Windows)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Checks out the repo to the runner

    - name: Install dependencies
      run: |
        # Add Microsoft package repository
        wget https://packages.microsoft.com/config/ubuntu/20.04/prod.list
        sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
        sudo apt update

        # Install .NET SDK (6.0 or other versions)
        sudo apt install -y dotnet-sdk-6.0

        # Install other dependencies (if needed)
        sudo apt install -y wget unzip curl

    - name: Download ASF Release
      run: |
        wget https://github.com/JustArchiNET/ArchiSteamFarm/releases/latest/download/ASF-linux-x64.zip  # Download ASF zip
        unzip ASF-linux-x64.zip -d ASF  # Unzip it into the ASF folder

    - name: Create Bot Config from Secrets
      run: |
        mkdir -p ASF-Bot/config  # Create the config folder if it doesn't exist
        echo "{
  "CustomGamePlayedWhileIdle": "Legit Farmer",
  "Enabled": true,
  "SteamLogin": "${{ secrets.STEAM_USERNAME1 }}",
  "SteamPassword": "${{ secrets.STEAM_PASSWORD1 }}",
  }
}" > ASF-Bot/config/Thomasjr.json  # Create a config file with your credentials and settings

    - name: Verify Bot Config Creation
      run: |
        ls -l ASF-Bot/config/  # List the config folder to verify the config file is created

    - name: Run ASF Bot
      run: |
        cd ASF  # Navigate to the ASF directory
        dotnet ArchiSteamFarm.dll --no-restart  # Run the ASF bot using dotnet
