name: ASF Bot (5 Accounts)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Restart every 6 hours

jobs:
  run-asf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget unzip

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Cache ASF binaries
      uses: actions/cache@v4
      with:
        path: |
          ASF
        key: ${{ runner.os }}-asf

    - name: Download and Extract ASF
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/JustArchiNET/ArchiSteamFarm/releases/latest/download/ASF-linux-x64.zip
        unzip ASF-linux-x64.zip -d ASF

    - name: Decode ASF .db file and place it in config folder
      run: |
        mkdir -p ASF/config  # Ensure the 'config' folder exists (this will not create the folder if it already exists)
        echo "${{ secrets.JONBZOMBIE_DB_FILE }}" | base64 --decode > ASF/config/JONBZOMBIE.db  # Decode the base64 encoded .db file and save it in the 'config' folder

    - name: Create config.json to enable the bot
      run: |
        echo '{
              "CustomGamePlayedWhileIdle": "Legit Farmer",
              "Enabled": true,
              "FarmingPreferences": 128,
              "HoursUntilCardDrops": 0
            }' > ASF/config/config.json  # Create config.json with the "Enabled": true flag  
        
    - name: Run ASF
      run: |
        cd ASF  # Go to ASF directory
        ls -l  # List files to ensure ArchiSteamFarm.dll exists
        ./ArchiSteamFarm --no-restart
