name: ASF Bot (5 Accounts)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Restart every 6 hours

jobs:
  run-asf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget unzip

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Cache ASF binaries
      uses: actions/cache@v4
      with:
        path: |
          ASF
        key: ${{ runner.os }}-asf

    - name: Download and Extract ASF
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/JustArchiNET/ArchiSteamFarm/releases/latest/download/ASF-linux-x64.zip
        unzip ASF.zip -d ASF

    - name: Create Bot Configs from Secrets
      run: |
        mkdir -p ASF/config
        cat > ASF/config/Thomasjr.json <<EOF
        {
          "Enabled": true,
          "SteamLogin": "${{ secrets.STEAM_USERNAME1 }}",
          "SteamPassword": "${{ secrets.STEAM_PASSWORD1 }}",
          "AutoSteamSaleEvent": true
        }
        EOF
        
    - name: Run ASF
      run: |
        cd ASF
        dotnet ArchiSteamFarm.dll --no-restart
